name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        super_secret: ${{ secrets.connectionstring }}
    - name: Install dependencies
      run: dotnet restore ConsoleApp1/ConsoleApp1.sln
    - name: Build
      run: dotnet build ConsoleApp1/ConsoleApp1.sln --configuration Release --no-restore
    - name: Run2
      run: dotnet run --project ConsoleApp1/ConsoleApp1/ConsoleApp1.csproj $super_secret
      env:
        super_secret: ${{ secrets.connectionstring }}
    - name: Status
      run: git status
